
------------------------------------------------------------------------------------------------
-- ROLE (2), USER_ACCOUNT (27), USER_DETAILS (25)
-- NOTE USERS: ADMIN ('superuser@admin.com', 'admin123!'), NORMAL: ('plain@user.com', 'user123!')

insert into role (role_name) values ('administrator');
insert into role (role_name) values ('webshop_user');

insert into user_account (uuid, email, password, role_id, created_on, last_login, active) values ('121aea07-4f3a-403f-a64a-3a9a44ec8ca8', 'smacwhirter0@dailymotion.com', 'FXv0aps7xAV2', 2, '2018-06-07 22:19:45', '2018-09-30 11:16:54', true);
insert into user_account (uuid, email, password, role_id, created_on, last_login, active) values ('abb629b0-5318-445d-9e2e-04394891b88d', 'rblumire1@businessinsider.com', 'JgC7yNJG', 2, '2019-04-03 16:07:31', '2018-07-02 06:19:39', true);
insert into user_account (uuid, email, password, role_id, created_on, last_login, active) values ('97f18026-7436-481b-b5a0-7e5bc08b96bb', 'amckinn2@w3.org', 'moZtF6kZ', 2, '2018-06-29 22:16:14', '2019-05-08 22:59:25', true);
insert into user_account (uuid, email, password, role_id, created_on, last_login, active) values ('c06ebaaa-9217-4e23-be8a-794b69765b12', 'rcrawford3@newyorker.com', 'IBF3MhY', 2, '2019-03-25 13:55:26', '2019-03-11 12:33:36', true);
insert into user_account (uuid, email, password, role_id, created_on, last_login, active) values ('0988031c-ad30-49aa-8fe6-deda8d3fd872', 'thallstone4@mayoclinic.com', '1HlrLbzr4Jy', 2, '2018-11-09 10:29:46', '2019-02-15 08:31:02', true);
insert into user_account (uuid, email, password, role_id, created_on, last_login, active) values ('2bfafb92-5403-40c7-a83e-88de772b6b2f', 'udallin5@qq.com', 'MN1HU5ihn', 2, '2018-11-19 14:00:55', '2019-01-19 08:00:07', true);
insert into user_account (uuid, email, password, role_id, created_on, last_login, active) values ('6c3e7e33-9830-46f6-b97a-94d8339fce97', 'jnineham6@bandcamp.com', '8ZLYOwNDsIq', 2, '2018-08-23 06:06:32', '2019-05-04 19:19:58', true);
insert into user_account (uuid, email, password, role_id, created_on, last_login, active) values ('2a1bf813-3381-40cc-84df-2adb0a51b70e', 'ipothergill7@aboutads.info', 'g5RokO', 2, '2018-10-14 04:57:41', '2018-05-21 06:09:40', true);
insert into user_account (uuid, email, password, role_id, created_on, last_login, active) values ('670e9c0b-2e9a-4af2-9ea5-775c85a21a1a', 'fscamp8@weebly.com', 'RsVif4WN', 2, '2018-06-01 04:54:19', '2019-01-30 19:08:34', true);
insert into user_account (uuid, email, password, role_id, created_on, last_login, active) values ('220ce959-fdc4-4435-8f08-0667503d0a9d', 'ecabrera9@dedecms.com', 'H4zXbR2D', 2, '2018-07-29 22:19:44', '2019-04-11 06:34:16', true);
insert into user_account (uuid, email, password, role_id, created_on, last_login, active) values ('54432243-26a0-4214-b6b2-a763ed485c91', 'cclethroa@people.com.cn', 'WncvKLSc4Ci', 2, '2018-05-31 09:49:30', '2018-05-19 15:46:04', true);
insert into user_account (uuid, email, password, role_id, created_on, last_login, active) values ('2393e615-c18a-46f3-8939-85b943c53dd3', 'fshuardb@hud.gov', 'gxyusm7', 2, '2018-12-18 11:14:16', '2018-05-11 03:08:26', true);
insert into user_account (uuid, email, password, role_id, created_on, last_login, active) values ('8e715860-e0b6-4a09-8b85-babc857ba71b', 'ntalc@mozilla.org', '7uVYuC2', 2, '2018-07-24 22:46:19', '2018-10-29 21:54:36', true);
insert into user_account (uuid, email, password, role_id, created_on, last_login, active) values ('cf36c8d4-d371-40ea-8b08-52dd98ec1529', 'apennellsd@jimdo.com', 'vtZpiq', 2, '2018-10-28 14:00:02', '2019-04-23 02:51:16', true);
insert into user_account (uuid, email, password, role_id, created_on, last_login, active) values ('ab55359a-4d61-47aa-9443-38d69e863faf', 'jbaffine@businessinsider.com', 'v48KP4BN', 2, '2019-05-04 17:01:33', '2019-01-02 00:52:33', true);
insert into user_account (uuid, email, password, role_id, created_on, last_login, active) values ('0b4c6379-1949-45fd-a641-b0f33a5a505b', 'kdatef@histats.com', 'ouVgYJM', 2, '2018-12-01 08:58:26', null, true);
insert into user_account (uuid, email, password, role_id, created_on, last_login, active) values ('e839afa0-a0d4-4cbc-bee0-ebac3599fd46', 'vmongerg@prlog.org', 'a5RqRZt', 2, '2018-06-06 23:30:02', '2018-06-22 15:19:49', true);
insert into user_account (uuid, email, password, role_id, created_on, last_login, active) values ('62695a09-6cf1-4348-aa9f-81ee7e59a91f', 'clystonh@netscape.com', 'IzDE6GA', 2, '2018-10-14 15:16:49', '2019-02-10 11:02:11', true);
insert into user_account (uuid, email, password, role_id, created_on, last_login, active) values ('d50fc8f5-47ae-4656-995d-2f2b5ac959ff', 'hhubbardi@trellian.com', '1VmZrvtR', 2, '2018-04-04 08:20:36', '2019-03-02 19:52:07', true);
insert into user_account (uuid, email, password, role_id, created_on, last_login, active) values ('fe0cca55-b2ba-46cd-92a9-08bfd10c45c6', 'cbykj@berkeley.edu', 'oCuT9XtHprdD', 2, '2018-06-17 06:27:16', null, true);
insert into user_account (uuid, email, password, role_id, created_on, last_login, active) values ('6ef7b1e0-7577-43ae-b3bc-008853716b65', 'plonsdalek@nih.gov', 'pqD5WwT9X', 2, '2019-04-04 05:12:43', '2018-09-25 14:25:48', true);
insert into user_account (uuid, email, password, role_id, created_on, last_login, active) values ('b8d897f4-1a6b-496f-b916-834e6579728e', 'fwardl@phpbb.com', 'ErR6fC', 2, '2018-06-06 00:23:07', '2018-09-15 01:07:44', true);
insert into user_account (uuid, email, password, role_id, created_on, last_login, active) values ('b97e6efa-9e20-4eca-80e2-ccd5a76fb913', 'bruddochm@bloglines.com', 'kxSh3kdlc', 2, '2018-09-10 05:41:41', '2018-11-07 10:10:28', true);
insert into user_account (uuid, email, password, role_id, created_on, last_login, active) values ('72de4a51-aa3a-482c-a232-0e1c52c1fe2f', 'gkerblern@cafepress.com', 'RXX7IgIM1E', 2, '2018-06-05 15:07:34', '2018-07-18 13:53:34', true);
insert into user_account (uuid, email, password, role_id, created_on, last_login, active) values ('8dc7040e-220a-49cc-ac5f-af028b7fa9ef', 'ulundono@opera.com', 'rScnwDFxvqk', 2, '2018-10-24 01:53:06', '2019-01-30 07:56:28', true);
insert into user_account (uuid, email, password, role_id, created_on, last_login, active) values ('97a754d3-3975-42f6-b6c5-c8acaa092062', 'superuser@admin.com', 'admin123!', 1, '2018-10-24 01:53:06', '2019-01-30 07:56:28', true);
insert into user_account (uuid, email, password, role_id, created_on, last_login, active) values ('c2046339-6a14-490b-881c-92c57973a602', 'plain@user.com', 'user123!', 2, '2018-10-24 01:53:06', '2019-01-30 07:56:28', true);


------------------------------------------------------------------------------------------------
-- LOGIN_LOG (102)

insert into login_log (username, ip_address, login_date, register) values ('plain@user.com', '135.152.248.251', '2019-06-03 09:32:31', true);
insert into login_log (username, ip_address, login_date, register) values ('plain@user.com', '135.152.248.251', '2019-06-04 09:32:31', false);
insert into login_log (username, ip_address, login_date, register) values ('rblumire1@businessinsider.com', '135.152.248.251', '2019-06-03 09:32:31', false);
insert into login_log (username, ip_address, login_date, register) values ('rblumire1@businessinsider.com', '213.145.72.143', '2019-07-02 05:59:49', false);
insert into login_log (username, ip_address, login_date, register) values ('rblumire1@businessinsider.com', '55.95.200.208', '2019-07-12 05:17:41', false);
insert into login_log (username, ip_address, login_date, register) values ('amckinn2@w3.org', '61.157.44.7', '2019-07-15 16:34:46', true);
insert into login_log (username, ip_address, login_date, register) values ('amckinn2@w3.org', '50.247.8.215', '2019-05-17 21:20:36', false);
insert into login_log (username, ip_address, login_date, register) values ('amckinn2@w3.org', '4.152.127.156', '2019-06-30 23:33:02', false);
insert into login_log (username, ip_address, login_date, register) values ('amckinn2@w3.org', '200.59.87.185', '2019-07-14 00:34:55', false);
insert into login_log (username, ip_address, login_date, register) values ('rcrawford3@newyorker.com', '48.225.188.110', '2019-05-27 10:57:19', true);
insert into login_log (username, ip_address, login_date, register) values ('rcrawford3@newyorker.com', '242.249.201.239', '2019-07-09 16:31:59', false);
insert into login_log (username, ip_address, login_date, register) values ('rcrawford3@newyorker.com', '126.165.62.15', '2019-07-11 02:13:57', false);
insert into login_log (username, ip_address, login_date, register) values ('thallstone4@mayoclinic.com', '209.130.128.18', '2019-06-09 13:19:33', true);
insert into login_log (username, ip_address, login_date, register) values ('thallstone4@mayoclinic.com', '15.129.137.35', '2019-05-03 03:07:30', false);
insert into login_log (username, ip_address, login_date, register) values ('thallstone4@mayoclinic.com', '120.221.17.136', '2019-06-14 21:20:34', false);
insert into login_log (username, ip_address, login_date, register) values ('thallstone4@mayoclinic.com', '212.192.26.169', '2019-05-22 23:50:41', false);
insert into login_log (username, ip_address, login_date, register) values ('udallin5@qq.com', '136.184.174.9', '2019-05-03 05:52:04', true);
insert into login_log (username, ip_address, login_date, register) values ('udallin5@qq.com', '80.82.28.181', '2019-06-09 02:57:18', false);
insert into login_log (username, ip_address, login_date, register) values ('udallin5@qq.com', '24.177.226.16', '2019-07-13 01:26:49', false);
insert into login_log (username, ip_address, login_date, register) values ('udallin5@qq.com', '108.18.54.92', '2019-07-15 05:33:06', false);
insert into login_log (username, ip_address, login_date, register) values ('jnineham6@bandcamp.com', '55.146.17.134', '2019-05-07 02:42:57', true);
insert into login_log (username, ip_address, login_date, register) values ('fscamp8@weebly.com', '103.179.107.107', '2019-06-03 16:29:51', true);
insert into login_log (username, ip_address, login_date, register) values ('ecabrera9@dedecms.com', '128.161.181.61', '2019-07-14 05:07:05', true);
insert into login_log (username, ip_address, login_date, register) values ('ecabrera9@dedecms.com', '193.100.118.80', '2019-06-12 00:18:23', false);
insert into login_log (username, ip_address, login_date, register) values ('cclethroa@people.com.cn', '23.160.160.130', '2019-05-09 11:24:52', true);
insert into login_log (username, ip_address, login_date, register) values ('cclethroa@people.com.cn', '213.203.36.231', '2019-06-26 16:01:44', false);
insert into login_log (username, ip_address, login_date, register) values ('cclethroa@people.com.cn', '42.69.145.168', '2019-05-26 02:07:19', false);
insert into login_log (username, ip_address, login_date, register) values ('cclethroa@people.com.cn', '60.42.185.39', '2019-07-15 22:26:56', false);
insert into login_log (username, ip_address, login_date, register) values ('cclethroa@people.com.cn', '29.62.231.53', '2019-06-05 16:29:15', false);
insert into login_log (username, ip_address, login_date, register) values ('cclethroa@people.com.cn', '56.68.140.80', '2019-05-01 14:04:05', false);
insert into login_log (username, ip_address, login_date, register) values ('cclethroa@people.com.cn', '242.37.137.248', '2019-05-15 23:02:50', false);
insert into login_log (username, ip_address, login_date, register) values ('cclethroa@people.com.cn', '169.27.116.163', '2019-06-05 16:42:45', false);
insert into login_log (username, ip_address, login_date, register) values ('cclethroa@people.com.cn', '37.183.175.111', '2019-05-03 00:57:15', false);
insert into login_log (username, ip_address, login_date, register) values ('fshuardb@hud.gov', '71.116.48.185', '2019-06-01 14:27:42', true);
insert into login_log (username, ip_address, login_date, register) values ('fshuardb@hud.gov', '61.22.205.137', '2019-06-21 08:12:49', false);
insert into login_log (username, ip_address, login_date, register) values ('fshuardb@hud.gov', '15.229.89.28', '2019-05-06 01:07:26', false);
insert into login_log (username, ip_address, login_date, register) values ('fshuardb@hud.gov', '239.150.115.12', '2019-05-12 05:35:18', false);
insert into login_log (username, ip_address, login_date, register) values ('fshuardb@hud.gov', '144.79.236.49', '2019-07-09 21:45:20', false);
insert into login_log (username, ip_address, login_date, register) values ('fshuardb@hud.gov', '31.167.152.183', '2019-05-29 18:43:59', false);
insert into login_log (username, ip_address, login_date, register) values ('ntalc@mozilla.org', '219.92.219.101', '2019-05-25 20:14:01', true);
insert into login_log (username, ip_address, login_date, register) values ('ntalc@mozilla.org', '45.192.152.163', '2019-06-03 03:50:19', false);
insert into login_log (username, ip_address, login_date, register) values ('ntalc@mozilla.org', '219.69.243.140', '2019-06-21 21:55:59', false);
insert into login_log (username, ip_address, login_date, register) values ('ntalc@mozilla.org', '209.164.83.111', '2019-05-07 19:44:25', false);
insert into login_log (username, ip_address, login_date, register) values ('ntalc@mozilla.org', '112.240.41.112', '2019-06-10 00:41:09', false);
insert into login_log (username, ip_address, login_date, register) values ('ntalc@mozilla.org', '217.103.46.233', '2019-07-08 13:57:31', false);
insert into login_log (username, ip_address, login_date, register) values ('apennellsd@jimdo.com', '134.130.219.217', '2019-05-01 22:45:42', true);
insert into login_log (username, ip_address, login_date, register) values ('apennellsd@jimdo.com', '28.244.118.201', '2019-05-03 15:53:08', false);
insert into login_log (username, ip_address, login_date, register) values ('apennellsd@jimdo.com', '107.227.65.120', '2019-07-10 21:22:57', false);
insert into login_log (username, ip_address, login_date, register) values ('apennellsd@jimdo.com', '88.207.36.2', '2019-06-01 02:50:12', false);
insert into login_log (username, ip_address, login_date, register) values ('jbaffine@businessinsider.com', '67.93.109.124', '2019-06-10 09:49:58', true);
insert into login_log (username, ip_address, login_date, register) values ('kdatef@histats.com', '223.187.15.211', '2019-07-11 13:28:33', false);
insert into login_log (username, ip_address, login_date, register) values ('kdatef@histats.com', '223.187.15.211', '2019-06-06 05:20:09', false);
insert into login_log (username, ip_address, login_date, register) values ('kdatef@histats.com', '223.187.15.211', '2019-05-09 16:47:33', true);
insert into login_log (username, ip_address, login_date, register) values ('vmongerg@prlog.org', '227.152.193.23', '2019-05-22 09:06:06', true);
insert into login_log (username, ip_address, login_date, register) values ('vmongerg@prlog.org', '50.70.211.125', '2019-06-02 07:48:53', false);
insert into login_log (username, ip_address, login_date, register) values ('clystonh@netscape.com', '89.146.46.89', '2019-06-03 15:55:14', true);
insert into login_log (username, ip_address, login_date, register) values ('clystonh@netscape.com', '24.115.88.199', '2019-05-09 03:42:53', false);
insert into login_log (username, ip_address, login_date, register) values ('clystonh@netscape.com', '119.194.109.4', '2019-05-02 07:19:05', false);
insert into login_log (username, ip_address, login_date, register) values ('hhubbardi@trellian.com', '83.179.151.144', '2019-05-10 15:11:26', true);
insert into login_log (username, ip_address, login_date, register) values ('hhubbardi@trellian.com', '204.93.252.107', '2019-05-19 08:50:58', false);
insert into login_log (username, ip_address, login_date, register) values ('hhubbardi@trellian.com', '110.190.203.96', '2019-06-17 06:10:13', false);
insert into login_log (username, ip_address, login_date, register) values ('hhubbardi@trellian.com', '239.140.16.19', '2019-05-22 07:46:28', false);
insert into login_log (username, ip_address, login_date, register) values ('cbykj@berkeley.edu', '75.26.139.66', '2019-07-15 17:10:07', true);
insert into login_log (username, ip_address, login_date, register) values ('cbykj@berkeley.edu', '2.114.83.110', '2019-05-15 02:38:34', false);
insert into login_log (username, ip_address, login_date, register) values ('cbykj@berkeley.edu', '226.173.180.37', '2019-05-28 02:43:07', false);
insert into login_log (username, ip_address, login_date, register) values ('cbykj@berkeley.edu', '226.24.179.55', '2019-05-31 12:10:22', false);
insert into login_log (username, ip_address, login_date, register) values ('cbykj@berkeley.edu', '59.162.95.15', '2019-05-12 19:16:01', false);
insert into login_log (username, ip_address, login_date, register) values ('plonsdalek@nih.gov', '25.20.106.39', '2019-06-29 03:48:05', true);
insert into login_log (username, ip_address, login_date, register) values ('plonsdalek@nih.gov', '192.118.80.108', '2019-05-02 06:06:45', false);
insert into login_log (username, ip_address, login_date, register) values ('plonsdalek@nih.gov', '204.42.164.56', '2019-06-08 21:22:50', false);
insert into login_log (username, ip_address, login_date, register) values ('plonsdalek@nih.gov', '159.221.84.245', '2019-05-01 04:34:55', false);
insert into login_log (username, ip_address, login_date, register) values ('plonsdalek@nih.gov', '26.52.172.107', '2019-06-19 15:22:24', false);
insert into login_log (username, ip_address, login_date, register) values ('plonsdalek@nih.gov', '158.193.113.7', '2019-05-25 12:19:47', false);
insert into login_log (username, ip_address, login_date, register) values ('fwardl@phpbb.com', '247.48.145.209', '2019-05-07 05:49:12', true);
insert into login_log (username, ip_address, login_date, register) values ('fwardl@phpbb.com', '222.248.54.232', '2019-05-27 07:40:26', false);
insert into login_log (username, ip_address, login_date, register) values ('fwardl@phpbb.com', '177.93.227.226', '2019-07-15 16:32:28', false);
insert into login_log (username, ip_address, login_date, register) values ('fwardl@phpbb.com', '18.16.237.230', '2019-06-12 21:18:44', false);
insert into login_log (username, ip_address, login_date, register) values ('fwardl@phpbb.com', '251.82.33.247', '2019-06-23 16:42:24', false);
insert into login_log (username, ip_address, login_date, register) values ('bruddochm@bloglines.com', '17.49.132.223', '2019-05-14 03:19:55', true);
insert into login_log (username, ip_address, login_date, register) values ('bruddochm@bloglines.com', '82.178.180.211', '2019-06-10 18:48:24', false);
insert into login_log (username, ip_address, login_date, register) values ('bruddochm@bloglines.com', '39.141.255.139', '2019-07-03 09:56:21', false);
insert into login_log (username, ip_address, login_date, register) values ('bruddochm@bloglines.com', '45.11.116.159', '2019-05-24 23:02:13', false);
insert into login_log (username, ip_address, login_date, register) values ('bruddochm@bloglines.com', '6.26.99.221', '2019-07-07 04:21:31', false);
insert into login_log (username, ip_address, login_date, register) values ('bruddochm@bloglines.com', '107.201.140.29', '2019-05-20 22:00:55', false);
insert into login_log (username, ip_address, login_date, register) values ('bruddochm@bloglines.com', '152.89.17.186', '2019-06-03 02:42:41', false);
insert into login_log (username, ip_address, login_date, register) values ('bruddochm@bloglines.com', '19.175.192.176', '2019-06-26 21:17:29', false);
insert into login_log (username, ip_address, login_date, register) values ('gkerblern@cafepress.com', '26.167.179.33', '2019-05-14 04:48:10', true);
insert into login_log (username, ip_address, login_date, register) values ('gkerblern@cafepress.com', '60.245.237.141', '2019-06-12 08:06:27', false);
insert into login_log (username, ip_address, login_date, register) values ('gkerblern@cafepress.com', '0.43.164.218', '2019-05-01 18:31:55', false);
insert into login_log (username, ip_address, login_date, register) values ('gkerblern@cafepress.com', '252.3.51.104', '2019-06-14 06:28:09', false);
insert into login_log (username, ip_address, login_date, register) values ('gkerblern@cafepress.com', '75.164.1.239', '2019-06-28 04:18:45', true);
insert into login_log (username, ip_address, login_date, register) values ('ulundono@opera.com', '250.94.151.217', '2019-07-11 14:01:34', true);
insert into login_log (username, ip_address, login_date, register) values ('ulundono@opera.com', '248.245.136.3', '2019-06-11 16:08:33', false);
insert into login_log (username, ip_address, login_date, register) values ('ulundono@opera.com', '136.73.48.93', '2019-05-18 13:51:40', false);
insert into login_log (username, ip_address, login_date, register) values ('ulundono@opera.com', '87.54.248.64', '2019-07-05 11:28:09', false);
insert into login_log (username, ip_address, login_date, register) values ('ulundono@opera.com', '46.213.167.184', '2019-06-18 18:57:00', false);
insert into login_log (username, ip_address, login_date, register) values ('ulundono@opera.com', '48.52.27.165', '2019-07-14 13:34:10', false);
insert into login_log (username, ip_address, login_date, register) values ('ulundono@opera.com', '3.65.32.108', '2019-06-30 13:04:32', false);
insert into login_log (username, ip_address, login_date, register) values ('ulundono@opera.com', '232.123.200.233', '2019-05-31 17:48:44', false);
insert into login_log (username, ip_address, login_date, register) values ('ulundono@opera.com', '143.104.246.183', '2019-06-24 13:50:56', false);
insert into login_log (username, ip_address, login_date, register) values ('smacwhirter0@dailymotion.com', '48.124.168.127', '2019-06-03 19:48:19', false);
insert into login_log (username, ip_address, login_date, register) values ('smacwhirter0@dailymotion.com', '85.138.214.65', '2019-05-07 08:18:39', true);


------------------------------------------------------------------------------------------------
-- CATEGORY (5), SUBCATEGORY (21), MANUFACTURER (50)

insert into product_category (name) values ('Games');
insert into product_category (name) values ('Books');
insert into product_category (name) values ('Gifts');
insert into product_category (name) values ('Models');
insert into product_category (name) values ('Accessories');

insert into product_subcategory (product_category_id, name) values (1, 'Board Games');
insert into product_subcategory (product_category_id, name) values (1, 'Role Playing Games');
insert into product_subcategory (product_category_id, name) values (1, 'Card Games');
insert into product_subcategory (product_category_id, name) values (1, 'Classical Games');
insert into product_subcategory (product_category_id, name) values (1, 'Party Games');

insert into product_subcategory (product_category_id, name) values (2, 'Fantasy Books');
insert into product_subcategory (product_category_id, name) values (2, 'Game Strategy Books');

insert into product_subcategory (product_category_id, name) values (3, 'Mugs');
insert into product_subcategory (product_category_id, name) values (3, 'Glasses');
insert into product_subcategory (product_category_id, name) values (3, 'Key Chains');
insert into product_subcategory (product_category_id, name) values (3, 'Miniatures');
insert into product_subcategory (product_category_id, name) values (3, 'Notebooks');
insert into product_subcategory (product_category_id, name) values (3, 'Coaters');
insert into product_subcategory (product_category_id, name) values (3, 'Plush Toys');

insert into product_subcategory (product_category_id, name) values (4, 'LEGO');
insert into product_subcategory (product_category_id, name) values (4, 'Airplane Models');
insert into product_subcategory (product_category_id, name) values (4, 'Car Models');

insert into product_subcategory (product_category_id, name) values (5, 'Card Sleeves');
insert into product_subcategory (product_category_id, name) values (5, 'Dice');
insert into product_subcategory (product_category_id, name) values (5, 'Writing Pads');
insert into product_subcategory (product_category_id, name) values (5, 'Tokens');

insert into product_manufacturer (name) values ('Kemmer, Bernhard and Dickens');
insert into product_manufacturer (name) values ('Stehr-Crooks');
insert into product_manufacturer (name) values ('Weissnat-Fadel');
insert into product_manufacturer (name) values ('Eichmann Inc');
insert into product_manufacturer (name) values ('Ullrich, Franecki and Schulist');
insert into product_manufacturer (name) values ('Wiza LLC');
insert into product_manufacturer (name) values ('Miller, Lang and Hauck');
insert into product_manufacturer (name) values ('Schuster-Abbott');
insert into product_manufacturer (name) values ('Hamill, Haag and Nitzsche');
insert into product_manufacturer (name) values ('Shields, Waelchi and Kreiger');
insert into product_manufacturer (name) values ('Weimann, Koepp and Towne');
insert into product_manufacturer (name) values ('Kshlerin-Pollich');
insert into product_manufacturer (name) values ('Hand, Vandervort and Ebert');
insert into product_manufacturer (name) values ('Emard and Sons');
insert into product_manufacturer (name) values ('Wuckert-Aufderhar');
insert into product_manufacturer (name) values ('Kling Group');
insert into product_manufacturer (name) values ('Hettinger Inc');
insert into product_manufacturer (name) values ('Hammes, Veum and Parker');
insert into product_manufacturer (name) values ('Kozey, Hudson and Bogan');
insert into product_manufacturer (name) values ('Howe Group');
insert into product_manufacturer (name) values ('Reilly Inc');
insert into product_manufacturer (name) values ('Langworth-Jenkins');
insert into product_manufacturer (name) values ('Littel-Braun');
insert into product_manufacturer (name) values ('Denesik LLC');
insert into product_manufacturer (name) values ('Corkery Group');
insert into product_manufacturer (name) values ('Eichmann, Pollich and Williamson');
insert into product_manufacturer (name) values ('Casper and Sons');
insert into product_manufacturer (name) values ('Pollich-Cartwright');
insert into product_manufacturer (name) values ('Reichel-Kautzer');
insert into product_manufacturer (name) values ('Lang and Sons');
insert into product_manufacturer (name) values ('Pfeffer, Heathcote and Franecki');
insert into product_manufacturer (name) values ('Doyle, Fahey and Dickinson');
insert into product_manufacturer (name) values ('Walter, Sipes and Hudson');
insert into product_manufacturer (name) values ('Strosin Inc');
insert into product_manufacturer (name) values ('Larson, Beer and Shanahan');
insert into product_manufacturer (name) values ('Rogahn-Olson');
insert into product_manufacturer (name) values ('Grant, Kozey and Rosenbaum');
insert into product_manufacturer (name) values ('Klein-Cassin');
insert into product_manufacturer (name) values ('Waelchi-O''Reilly');
insert into product_manufacturer (name) values ('Huels, Langosh and Wyman');
insert into product_manufacturer (name) values ('Morissette-Mueller');
insert into product_manufacturer (name) values ('Runolfsdottir Group');
insert into product_manufacturer (name) values ('Mueller Inc');
insert into product_manufacturer (name) values ('Green, Treutel and Powlowski');
insert into product_manufacturer (name) values ('Greenfelder and Sons');
insert into product_manufacturer (name) values ('Krajcik, Kassulke and Schmidt');
insert into product_manufacturer (name) values ('Effertz and Sons');
insert into product_manufacturer (name) values ('Bartoletti, Bernhard and Bednar');
insert into product_manufacturer (name) values ('Jacobson, Marquardt and Kub');
insert into product_manufacturer (name) values ('Kuhn-Schultz');

------------------------------------------------------------------------------------------------
-- PRODUCT (150, of which 1:24 - BOARD GAMES, 138:150 - EXPANSIONS), GAME DETAILS (24), EXPANSION DETAILS (13)

insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (1, 47, 'Settlers of Catan', 'nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum', 'https://picsum.photos/id/21/250/250', 'http://phoca.cz/eleifend/donec.xml', 379.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (1, 49, 'Puerto Rico', 'molestie lorem quisque ut erat curabitur gravida nisi at nibh', 'https://picsum.photos/id/22/250/250', 'https://skyrock.com/duis.js', 379.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (1, 17, 'Carcassonne', 'massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien', 'https://picsum.photos/id/23/250/250', 'https://ning.com/praesent/blandit/nam.xml', 379.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (1, 2, 'Citadels', 'convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet', 'https://picsum.photos/id/24/250/250', 'https://biglobe.ne.jp/cras/non/velit.json', 379.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (1, 34, 'Pandemic', 'metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend', 'https://picsum.photos/id/25/250/250', 'http://youku.com/metus/arcu/adipiscing/molestie/hendrerit/at/vulputate.js', 469.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (1, 28, 'Small World', 'felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus', 'https://picsum.photos/id/26/250/250', 'http://upenn.edu/lorem/vitae/mattis.jpg', 469.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (1, 50, 'This War of Mine', 'id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi', 'https://picsum.photos/id/27/250/250', 'https://twitpic.com/nam/ultrices/libero/non.jsp', 469.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (1, 23, 'Terraforming Mars', 'at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci', 'https://picsum.photos/id/28/250/250', 'http://webmd.com/feugiat/et/eros/vestibulum.json', 299.49);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (1, 44, 'Through the Ages', 'sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis', 'https://picsum.photos/id/29/250/250', 'http://twitpic.com/pellentesque/ultrices/phasellus/id/sapien.html', 194.35);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (1, 21, '7 Wonders', 'est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien', 'https://picsum.photos/id/10/250/250', 'https://youku.com/justo/sit/amet/sapien.png', 437.60);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (1, 9, 'Powergrid', 'phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque', 'https://picsum.photos/id/11/250/250', 'https://constantcontact.com/integer/tincidunt/ante/vel.jsp', 337.72);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (1, 39, 'King of Tokyo', 'nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in', 'https://picsum.photos/id/12/250/250', 'https://amazonaws.com/sem/praesent/id/massa.json', 155.81);

insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (1, 47, 'Gloomhaven', 'nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum', 'https://picsum.photos/id/13/250/250', 'http://phoca.cz/eleifend/donec.xml', 379.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (1, 49, 'Twilight Struggle', 'molestie lorem quisque ut erat curabitur gravida nisi at nibh', 'https://picsum.photos/id/14/250/250', 'https://skyrock.com/duis.js', 379.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (1, 17, 'Scythe', 'massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien', 'https://picsum.photos/id/15/250/250', 'https://ning.com/praesent/blandit/nam.xml', 379.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (1, 2, 'Spirit Island', 'convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet', 'https://picsum.photos/id/16/250/250', 'https://biglobe.ne.jp/cras/non/velit.json', 379.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (1, 34, 'Concordia', 'metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend', 'https://picsum.photos/id/17/250/250', 'http://youku.com/metus/arcu/adipiscing/molestie/hendrerit/at/vulputate.js', 469.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (1, 28, 'Ticket to Ride', 'felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus', 'https://picsum.photos/id/18/250/250', 'http://upenn.edu/lorem/vitae/mattis.jpg', 469.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (1, 50, 'Arkam Horror', 'id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi', 'https://picsum.photos/id/19/250/250', 'https://twitpic.com/nam/ultrices/libero/non.jsp', 469.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (1, 23, 'Betrayal on the House on the Hill', 'at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci', 'https://picsum.photos/id/20/250/250', 'http://webmd.com/feugiat/et/eros/vestibulum.json', 299.49);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (1, 44, 'Agricola', 'sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis', 'https://picsum.photos/id/21/250/250', 'http://twitpic.com/pellentesque/ultrices/phasellus/id/sapien.html', 194.35);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (1, 21, 'Blood Rage', 'est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien', 'https://picsum.photos/id/22/250/250', 'https://youku.com/justo/sit/amet/sapien.png', 437.60);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (1, 9, 'Azul', 'phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque', 'https://picsum.photos/id/23/250/250', 'https://constantcontact.com/integer/tincidunt/ante/vel.jsp', 337.72);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (1, 39, 'Caylus', 'nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in', 'https://picsum.photos/id/24/250/250', 'https://amazonaws.com/sem/praesent/id/massa.json', 155.81);

insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (2, 42, 'Dungeons and Dragons Base Game', 'platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat', 'https://picsum.photos/id/25/250/250', 'https://last.fm/turpis/enim/blandit/mi/in/porttitor/pede.html', 423.18);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (2, 12, 'Vampire Lore', 'scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a', 'https://picsum.photos/id/26/250/250', 'http://pagesperso-orange.fr/lacus/morbi/quis/tortor/id.jpg', 214.94);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (2, 7, 'Game of Thrones RPG', 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra', 'https://picsum.photos/id/27/250/250', 'https://webmd.com/sem/praesent.aspx', 106.44);

insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (3, 6, '7 Wonders Duel', 'erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non', 'https://picsum.photos/id/28/250/250', 'http://typepad.com/eros/elementum/pellentesque/quisque.aspx', 302.94);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (3, 18, 'Pokemon', 'ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices', 'https://picsum.photos/id/29/250/250', 'http://ow.ly/feugiat/et/eros/vestibulum.jpg', 489.90);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (3, 6, 'Bang!', 'vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra', 'https://picsum.photos/id/30/250/250', 'https://businesswire.com/turpis/enim/blandit/mi/in.jsp', 217.42);

insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (4, 8, 'Chess', 'ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam', 'https://picsum.photos/id/31/250/250', 'http://merriam-webster.com/platea/dictumst/maecenas.html', 442.26);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (4, 49, 'Backgammon', 'neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus', 'https://picsum.photos/id/32/250/250', 'https://opensource.org/rhoncus/aliquet/pulvinar/sed.png', 415.09);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (4, 43, 'Go', 'elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien', 'https://picsum.photos/id/33/250/250', 'https://ucoz.ru/magna/bibendum/imperdiet/nullam.jpg', 328.57);

insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (5, 29, 'Alias', 'faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at', 'https://picsum.photos/id/34/250/250', 'http://google.pl/dolor/quis/odio/consequat/varius/integer.xml', 250);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (5, 37, 'Pictionary', 'turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam', 'https://picsum.photos/id/35/250/250', 'https://earthlink.net/morbi/porttitor/lorem/id/ligula.jpg', 250);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (5, 46, 'Codenames', 'aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque', 'https://picsum.photos/id/36/250/250', 'https://prnewswire.com/orci/luctus/et.json', 250);

insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (6, 41, 'Witcher', 'in sagittis dui vel nisl duis ac nibh fusce lacus purus', 'https://picsum.photos/id/37/250/250', 'https://jiathis.com/dolor/quis.jsp', 200);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (6, 36, 'Game of Thrones', 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam', 'https://picsum.photos/id/38/250/250', 'http://cnbc.com/donec/ut/mauris.js', 200);

insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (7, 48, 'Chess for Dummies', 'erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate', 'https://picsum.photos/id/39/250/250', 'http://biglobe.ne.jp/enim/in/tempor.aspx', 150);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (7, 15, 'Go for Dummies', 'at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non', 'https://picsum.photos/id/40/250/250', 'https://skype.com/accumsan/tellus/nisi/eu/orci/mauris/lacinia.html', 150);

insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (8, 45, 'GoT mug - Stark', 'condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit', 'https://picsum.photos/id/41/250/250', 'http://reference.com/ultrices/mattis/odio/donec/vitae/nisi.png', 150);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (8, 17, 'GoT mug - Mormont', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede', 'https://picsum.photos/id/42/250/250', 'http://npr.org/consequat/morbi/a/ipsum/integer/a.js', 150);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (8, 17, 'Rick and Morty mug', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede', 'https://picsum.photos/id/43/250/250', 'http://npr.org/consequat/morbi/a/ipsum/integer/a.js', 150);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (8, 17, 'Stormtrooper mug', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede', 'https://picsum.photos/id/44/250/250', 'http://npr.org/consequat/morbi/a/ipsum/integer/a.js', 150);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (8, 17, 'Darth Vader mug', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede', 'https://picsum.photos/id/45/250/250', 'http://npr.org/consequat/morbi/a/ipsum/integer/a.js', 150);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (8, 17, 'Adventuretime mug', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede', 'https://picsum.photos/id/46/250/250', 'http://npr.org/consequat/morbi/a/ipsum/integer/a.js', 150);

insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (9, 17, 'Adventuretime glass', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede', 'https://picsum.photos/id/47/250/250', 'http://npr.org/consequat/morbi/a/ipsum/integer/a.js', 100);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (9, 17, 'Avengers glass', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede', 'https://picsum.photos/id/48/250/250', 'http://npr.org/consequat/morbi/a/ipsum/integer/a.js', 100);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (9, 17, 'Stormtrooper glass', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede', 'https://picsum.photos/id/49/250/250', 'http://npr.org/consequat/morbi/a/ipsum/integer/a.js', 100);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (9, 17, 'Darth Vader glass', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede', 'https://picsum.photos/id/50/250/250', 'http://npr.org/consequat/morbi/a/ipsum/integer/a.js', 100);

insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (10, 45, 'GoT keychain - Stark', 'condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit', 'https://picsum.photos/id/51/250/250', 'http://reference.com/ultrices/mattis/odio/donec/vitae/nisi.png', 67.87);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (10, 17, 'GoT keychain - Mormont', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede', 'https://picsum.photos/id/52/250/250', 'http://npr.org/consequat/morbi/a/ipsum/integer/a.js', 67.87);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (10, 17, 'Rick and Morty keychain', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede', 'https://picsum.photos/id/52/250/250', 'http://npr.org/consequat/morbi/a/ipsum/integer/a.js', 67.87);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (10, 17, 'Stormtrooper keychain', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede', 'https://picsum.photos/id/52/250/250', 'http://npr.org/consequat/morbi/a/ipsum/integer/a.js', 67.87);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (10, 17, 'Darth Vader keychain', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede', 'https://picsum.photos/id/52/250/250', 'http://npr.org/consequat/morbi/a/ipsum/integer/a.js', 67.87);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (10, 17, 'Adventuretime keychain', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede', 'https://picsum.photos/id/52/250/250', 'http://npr.org/consequat/morbi/a/ipsum/integer/a.js', 67.87);

insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (11, 12, 'Stormtrooper miniature', 'hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat', 'https://picsum.photos/id/53/250/250', 'https://npr.org/arcu/sed.jpg', 77.87);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (11, 12, 'Darth Vader miniature', 'hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat', 'https://picsum.photos/id/53/250/250', 'https://npr.org/arcu/sed.jpg', 77.87);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (11, 12, 'Spiderman miniature', 'hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat', 'https://picsum.photos/id/53/250/250', 'https://npr.org/arcu/sed.jpg', 77.87);

insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (12, 45, 'GoT notebook - Stark', 'condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit', 'https://picsum.photos/id/54/250/250', 'http://reference.com/ultrices/mattis/odio/donec/vitae/nisi.png', 59.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (12, 17, 'GoT notebook - Mormont', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede', 'https://picsum.photos/id/54/250/250', 'http://npr.org/consequat/morbi/a/ipsum/integer/a.js', 59.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (12, 17, 'Rick and Morty notebook', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede', 'https://picsum.photos/id/54/250/250', 'http://npr.org/consequat/morbi/a/ipsum/integer/a.js', 59.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (12, 17, 'Stormtrooper notebook', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede', 'https://picsum.photos/id/54/250/250', 'http://npr.org/consequat/morbi/a/ipsum/integer/a.js', 59.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (12, 17, 'Darth Vader notebook', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede', 'https://picsum.photos/id/54/250/250', 'http://npr.org/consequat/morbi/a/ipsum/integer/a.js', 59.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (12, 17, 'Adventuretime notebook', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede', 'https://picsum.photos/id/54/250/250', 'http://npr.org/consequat/morbi/a/ipsum/integer/a.js', 59.99);

insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (13, 45, 'GoT coaters - Stark', 'condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit', 'https://picsum.photos/id/55/250/250', 'http://reference.com/ultrices/mattis/odio/donec/vitae/nisi.png', 97.77);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (13, 17, 'GoT coaters - Mormont', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede', 'https://picsum.photos/id/55/250/250', 'http://npr.org/consequat/morbi/a/ipsum/integer/a.js', 97.77);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (13, 17, 'Rick and Morty coaters', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede', 'https://picsum.photos/id/55/250/250', 'http://npr.org/consequat/morbi/a/ipsum/integer/a.js', 97.77);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (13, 17, 'Stormtrooper coaters', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede', 'https://picsum.photos/id/55/250/250', 'http://npr.org/consequat/morbi/a/ipsum/integer/a.js', 97.77);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (13, 17, 'Darth Vader coaters', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede', 'https://picsum.photos/id/55/250/250', 'http://npr.org/consequat/morbi/a/ipsum/integer/a.js', 97.77);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (13, 17, 'Adventuretime coaters', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede', 'https://picsum.photos/id/55/250/250', 'http://npr.org/consequat/morbi/a/ipsum/integer/a.js', 97.77);

insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (14, 48, 'Killer Rabbit toy', 'nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec', 'https://picsum.photos/id/54/250/250', 'http://go.com/rhoncus/dui/vel/sem/sed.aspx', 150.43);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (14, 48, 'Jack the Dog toy', 'nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec', 'https://picsum.photos/id/54/250/250', 'http://go.com/rhoncus/dui/vel/sem/sed.aspx', 150.43);

insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (15, 1, 'Frozen LEGO', 'ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec', 'https://picsum.photos/id/57/250/250', 'https://odnoklassniki.ru/nibh/in/quis/justo/maecenas/rhoncus.jpg', 755.52);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (15, 1, 'Star Wars LEGO', 'ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec', 'https://picsum.photos/id/57/250/250', 'https://odnoklassniki.ru/nibh/in/quis/justo/maecenas/rhoncus.jpg', 755.52);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (15, 1, 'Race LEGO', 'ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec', 'https://picsum.photos/id/57/250/250', 'https://odnoklassniki.ru/nibh/in/quis/justo/maecenas/rhoncus.jpg', 755.52);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (15, 1, 'Underwater Station LEGO', 'ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec', 'https://picsum.photos/id/57/250/250', 'https://odnoklassniki.ru/nibh/in/quis/justo/maecenas/rhoncus.jpg', 755.52);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (15, 1, 'Urban City LEGO', 'ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec', 'https://picsum.photos/id/57/250/250', 'https://odnoklassniki.ru/nibh/in/quis/justo/maecenas/rhoncus.jpg', 755.52);

insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (16, 2, 'Airplane FT721', 'felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus', 'https://picsum.photos/id/58/250/250', 'http://howstuffworks.com/penatibus/et/magnis/dis/parturient.html', 399.99);

insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (17, 41, 'Tank', 'sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non', 'https://picsum.photos/id/59/250/250', 'https://naver.com/ac/lobortis/vel/dapibus/at.png', 422.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (17, 27, 'Batmobile', 'fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu', 'https://picsum.photos/id/59/250/250', 'http://elpais.com/maecenas/tristique/est.js', 459.99);

insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (18, 16, 'Card sleeves S - 100, transparent', 'proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis', 'https://picsum.photos/id/60/250/250', 'https://e-recht24.de/a/odio/in/hac/habitasse/platea.html', 27.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (18, 12, 'Card sleeves S - 200, transparent', 'ut massa quis augue luctus tincidunt nulla mollis molestie lorem', 'https://picsum.photos/id/60/250/250', 'http://wix.com/at/vulputate/vitae/nisl.xml', 39.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (18, 12, 'Card sleeves S - 100, yellow', 'ut massa quis augue luctus tincidunt nulla mollis molestie lorem', 'https://picsum.photos/id/60/250/250', 'http://wix.com/at/vulputate/vitae/nisl.xml', 29.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (18, 12, 'Card sleeves S - 100, blue', 'ut massa quis augue luctus tincidunt nulla mollis molestie lorem', 'https://picsum.photos/id/60/250/250', 'http://wix.com/at/vulputate/vitae/nisl.xml', 29.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (18, 12, 'Card sleeves M - 100, transparent', 'ut massa quis augue luctus tincidunt nulla mollis molestie lorem', 'https://picsum.photos/id/60/250/250', 'http://wix.com/at/vulputate/vitae/nisl.xml', 37.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (18, 12, 'Card sleeves M - 100, yellow', 'ut massa quis augue luctus tincidunt nulla mollis molestie lorem', 'https://picsum.photos/id/60/250/250', 'http://wix.com/at/vulputate/vitae/nisl.xml', 37.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (18, 12, 'Card sleeves M - 100, blue', 'ut massa quis augue luctus tincidunt nulla mollis molestie lorem', 'https://picsum.photos/id/60/250/250', 'http://wix.com/at/vulputate/vitae/nisl.xml', 37.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (18, 12, 'Card sleeves M - 100, red', 'ut massa quis augue luctus tincidunt nulla mollis molestie lorem', 'https://picsum.photos/id/60/250/250', 'http://wix.com/at/vulputate/vitae/nisl.xml', 37.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (18, 12, 'Card sleeves M - 100, green', 'ut massa quis augue luctus tincidunt nulla mollis molestie lorem', 'https://picsum.photos/id/60/250/250', 'http://wix.com/at/vulputate/vitae/nisl.xml', 37.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (18, 12, 'Card sleeves L - 100, transparent', 'ut massa quis augue luctus tincidunt nulla mollis molestie lorem', 'https://picsum.photos/id/60/250/250', 'http://wix.com/at/vulputate/vitae/nisl.xml', 42.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (18, 12, 'Card sleeves L - 100, yellow', 'ut massa quis augue luctus tincidunt nulla mollis molestie lorem', 'https://picsum.photos/id/60/250/250', 'http://wix.com/at/vulputate/vitae/nisl.xml', 42.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (18, 12, 'Card sleeves L - 100, blue', 'ut massa quis augue luctus tincidunt nulla mollis molestie lorem', 'https://picsum.photos/id/60/250/250', 'http://wix.com/at/vulputate/vitae/nisl.xml', 42.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (18, 12, 'Card sleeves L - 100, red', 'ut massa quis augue luctus tincidunt nulla mollis molestie lorem', 'https://picsum.photos/id/60/250/250', 'http://wix.com/at/vulputate/vitae/nisl.xml', 42.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (18, 12, 'Card sleeves L - 100, green', 'ut massa quis augue luctus tincidunt nulla mollis molestie lorem', 'https://picsum.photos/id/60/250/250', 'http://wix.com/at/vulputate/vitae/nisl.xml', 42.99);

insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (19, 21, 'Dice D4 - white', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 'https://picsum.photos/id/61/250/250', 'http://google.ca/cubilia/curae/mauris/viverra/diam/vitae/quam.xml', 22.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (19, 21, 'Dice D4 - yellow', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 'https://picsum.photos/id/61/250/250', 'http://google.ca/cubilia/curae/mauris/viverra/diam/vitae/quam.xml', 22.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (19, 21, 'Dice D4 - red', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 'https://picsum.photos/id/61/250/250', 'http://google.ca/cubilia/curae/mauris/viverra/diam/vitae/quam.xml', 22.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (19, 21, 'Dice D4 - blue', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 'https://picsum.photos/id/61/250/250', 'http://google.ca/cubilia/curae/mauris/viverra/diam/vitae/quam.xml', 22.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (19, 21, 'Dice D4 - green', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 'https://picsum.photos/id/61/250/250', 'http://google.ca/cubilia/curae/mauris/viverra/diam/vitae/quam.xml', 22.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (19, 21, 'Dice D4 - black', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 'https://picsum.photos/id/61/250/250', 'http://google.ca/cubilia/curae/mauris/viverra/diam/vitae/quam.xml', 22.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (19, 21, 'Dice D4 - purple', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 'https://picsum.photos/id/61/250/250', 'http://google.ca/cubilia/curae/mauris/viverra/diam/vitae/quam.xml', 22.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (19, 21, 'Dice D6 - white', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 'https://picsum.photos/id/61/250/250', 'http://google.ca/cubilia/curae/mauris/viverra/diam/vitae/quam.xml', 33.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (19, 21, 'Dice D6 - yellow', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 'https://picsum.photos/id/61/250/250', 'http://google.ca/cubilia/curae/mauris/viverra/diam/vitae/quam.xml', 33.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (19, 21, 'Dice D6 - red', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 'https://picsum.photos/id/61/250/250', 'http://google.ca/cubilia/curae/mauris/viverra/diam/vitae/quam.xml', 33.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (19, 21, 'Dice D6 - blue', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 'https://picsum.photos/id/61/250/250', 'http://google.ca/cubilia/curae/mauris/viverra/diam/vitae/quam.xml', 33.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (19, 21, 'Dice D6 - green', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 'https://picsum.photos/id/61/250/250', 'http://google.ca/cubilia/curae/mauris/viverra/diam/vitae/quam.xml', 33.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (19, 21, 'Dice D6 - black', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 'https://picsum.photos/id/61/250/250', 'http://google.ca/cubilia/curae/mauris/viverra/diam/vitae/quam.xml', 33.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (19, 21, 'Dice D6 - purple', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 'https://picsum.photos/id/61/250/250', 'http://google.ca/cubilia/curae/mauris/viverra/diam/vitae/quam.xml', 33.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (19, 21, 'Dice D10 - white', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 'https://picsum.photos/id/61/250/250', 'http://google.ca/cubilia/curae/mauris/viverra/diam/vitae/quam.xml', 37.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (19, 21, 'Dice D10 - yellow', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 'https://picsum.photos/id/61/250/250', 'http://google.ca/cubilia/curae/mauris/viverra/diam/vitae/quam.xml', 37.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (19, 21, 'Dice D10 - red', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 'https://picsum.photos/id/61/250/250', 'http://google.ca/cubilia/curae/mauris/viverra/diam/vitae/quam.xml', 37.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (19, 21, 'Dice D10 - blue', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 'https://picsum.photos/id/61/250/250', 'http://google.ca/cubilia/curae/mauris/viverra/diam/vitae/quam.xml', 37.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (19, 21, 'Dice D10 - green', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 'https://picsum.photos/id/61/250/250', 'http://google.ca/cubilia/curae/mauris/viverra/diam/vitae/quam.xml', 37.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (19, 21, 'Dice D10 - black', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 'https://picsum.photos/id/61/250/250', 'http://google.ca/cubilia/curae/mauris/viverra/diam/vitae/quam.xml', 37.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (19, 21, 'Dice D10 - purple', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 'https://picsum.photos/id/61/250/250', 'http://google.ca/cubilia/curae/mauris/viverra/diam/vitae/quam.xml', 37.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (19, 21, 'Dice D20 - white', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 'https://picsum.photos/id/61/250/250', 'http://google.ca/cubilia/curae/mauris/viverra/diam/vitae/quam.xml', 39.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (19, 21, 'Dice D20 - yellow', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 'https://picsum.photos/id/61/250/250', 'http://google.ca/cubilia/curae/mauris/viverra/diam/vitae/quam.xml', 39.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (19, 21, 'Dice D20 - red', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 'https://picsum.photos/id/61/250/250', 'http://google.ca/cubilia/curae/mauris/viverra/diam/vitae/quam.xml', 39.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (19, 21, 'Dice D20 - blue', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 'https://picsum.photos/id/61/250/250', 'http://google.ca/cubilia/curae/mauris/viverra/diam/vitae/quam.xml', 39.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (19, 21, 'Dice D20 - green', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 'https://picsum.photos/id/61/250/250', 'http://google.ca/cubilia/curae/mauris/viverra/diam/vitae/quam.xml', 39.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (19, 21, 'Dice D20 - black', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 'https://picsum.photos/id/61/250/250', 'http://google.ca/cubilia/curae/mauris/viverra/diam/vitae/quam.xml', 39.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (19, 21, 'Dice D20 - purple', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 'https://picsum.photos/id/61/250/250', 'http://google.ca/cubilia/curae/mauris/viverra/diam/vitae/quam.xml', 39.78);

insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (20, 24, '7 Wonders scoring pad', 'at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt', 'https://picsum.photos/id/62/250/250', 'http://kickstarter.com/parturient.xml', 57.78);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (20, 25, 'DnD Character Sheets', 'a pede posuere nonummy integer non velit donec diam neque vestibulum eget', 'https://picsum.photos/id/62/250/250', 'http://gnu.org/nulla/sed.json', 77.78);

insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (21, 19, 'Plastic cubes - S, yellow', 'enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices', 'https://picsum.photos/id/63/250/250', 'http://dion.ne.jp/ac/nulla/sed/vel/enim/sit/amet.png', 49.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (21, 19, 'Plastic cubes - S, red', 'enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices', 'https://picsum.photos/id/63/250/250', 'http://dion.ne.jp/ac/nulla/sed/vel/enim/sit/amet.png', 49.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (21, 19, 'Plastic cubes - S, blue', 'enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices', 'https://picsum.photos/id/63/250/250', 'http://dion.ne.jp/ac/nulla/sed/vel/enim/sit/amet.png', 49.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (21, 19, 'Plastic cubes - M, yellow', 'enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices', 'https://picsum.photos/id/63/250/250', 'http://dion.ne.jp/ac/nulla/sed/vel/enim/sit/amet.png', 79.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (21, 19, 'Plastic cubes - M, red', 'enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices', 'https://picsum.photos/id/63/250/250', 'http://dion.ne.jp/ac/nulla/sed/vel/enim/sit/amet.png', 79.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (21, 19, 'Plastic cubes - M, blue', 'enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices', 'https://picsum.photos/id/63/250/250', 'http://dion.ne.jp/ac/nulla/sed/vel/enim/sit/amet.png', 79.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (21, 19, 'Plastic chips - S, yellow', 'enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices', 'https://picsum.photos/id/63/250/250', 'http://dion.ne.jp/ac/nulla/sed/vel/enim/sit/amet.png', 39.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (21, 19, 'Plastic chips - S, red', 'enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices', 'https://picsum.photos/id/63/250/250', 'http://dion.ne.jp/ac/nulla/sed/vel/enim/sit/amet.png', 39.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (21, 19, 'Plastic chips - S, blue', 'enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices', 'https://picsum.photos/id/63/250/250', 'http://dion.ne.jp/ac/nulla/sed/vel/enim/sit/amet.png', 39.99);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (21, 19, 'Plastic chips - M, yellow', 'enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices', 'https://picsum.photos/id/63/250/250', 'http://dion.ne.jp/ac/nulla/sed/vel/enim/sit/amet.png', 47.79);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (21, 19, 'Plastic chips - M, red', 'enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices', 'https://picsum.photos/id/63/250/250', 'http://dion.ne.jp/ac/nulla/sed/vel/enim/sit/amet.png', 47.79);
insert into product (product_subcategory_id, product_manufacturer_id, name, description, picture_url, external_url, price) values (21, 19, 'Plastic chips - M, blue', 'enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices', 'https://picsum.photos/id/63/250/250', 'http://dion.ne.jp/ac/nulla/sed/vel/enim/sit/amet.png', 47.79);

------------------------------------------------------------------------------------------------
-- RECEIPT (50), ITEM (137)

insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (25, '498539171-9', false, '2019-03-16 00:01:03');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (23, '694839145-1', true, '2018-05-31 13:39:47');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (11, '412135911-9', false, '2019-04-12 06:41:43');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (13, '314304101-3', false, '2019-05-07 16:23:58');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (11, '271049269-5', true, '2018-07-19 00:58:50');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (6, '697374677-2', true, '2018-10-31 15:22:09');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (1, '944885408-0', false, '2019-03-21 01:04:46');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (13, '695216917-2', true, '2019-01-13 08:11:49');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (6, '743578726-4', true, '2019-04-08 04:23:21');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (2, '894408020-8', true, '2019-02-15 03:18:45');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (23, '140194018-8', false, '2019-04-16 18:19:41');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (16, '681647710-3', true, '2018-12-19 00:40:00');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (8, '203796521-4', true, '2019-01-06 09:19:01');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (20, '467128155-4', false, '2019-02-28 21:36:15');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (22, '563160369-1', false, '2018-11-19 00:44:44');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (1, '388585923-8', false, '2018-07-26 12:50:40');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (23, '718539208-X', true, '2018-09-28 04:03:53');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (11, '011219503-2', true, '2018-09-25 10:47:36');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (7, '941201354-X', false, '2019-01-23 17:34:42');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (15, '695609087-2', false, '2018-05-28 18:15:03');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (13, '479154705-5', false, '2019-04-04 21:14:33');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (16, '140600283-6', false, '2018-07-08 07:49:44');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (7, '798769880-6', true, '2018-08-13 08:29:14');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (4, '974744144-6', true, '2018-11-25 04:56:15');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (13, '107995696-4', false, '2019-04-30 09:36:19');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (4, '246028330-X', false, '2019-02-18 03:52:26');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (9, '084603939-7', false, '2018-08-20 14:22:28');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (17, '145000276-5', true, '2018-11-25 00:16:06');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (9, '267793585-6', false, '2018-06-01 16:18:49');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (4, '735613461-6', false, '2018-08-21 16:54:33');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (25, '925258429-3', false, '2018-09-15 16:49:35');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (14, '511186246-3', false, '2018-11-09 21:01:34');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (13, '725180219-8', true, '2018-09-27 01:45:50');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (8, '332207663-6', true, '2019-04-07 05:51:57');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (22, '905165993-8', false, '2018-12-29 22:37:48');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (9, '921021155-3', true, '2018-10-24 17:09:17');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (17, '436620601-3', false, '2018-08-01 03:19:42');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (2, '393371038-3', true, '2018-04-28 06:09:59');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (20, '859385771-X', true, '2018-09-08 12:29:20');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (2, '488757470-3', false, '2018-06-04 20:58:20');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (19, '081898430-9', true, '2019-04-05 05:06:56');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (4, '339991992-1', true, '2018-09-01 05:35:00');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (4, '004507604-9', false, '2018-09-08 05:16:36');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (18, '206237136-5', false, '2018-08-24 20:10:22');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (11, '979455949-0', true, '2019-04-01 04:21:34');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (11, '025061933-4', true, '2019-04-03 16:11:57');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (1, '264374145-5', true, '2018-09-24 23:30:48');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (8, '496765176-3', true, '2018-08-31 06:24:58');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (11, '355347247-2', false, '2018-10-06 14:24:34');
insert into receipt (user_account_id, receipt_number, credit_card, purchase_date) values (15, '447287544-6', false, '2018-06-24 04:26:11');

insert into receipt_item (receipt_id, product_id, amount) values (1, 76, 3);
insert into receipt_item (receipt_id, product_id, amount) values (2, 4, 2);
insert into receipt_item (receipt_id, product_id, amount) values (3, 80, 1);
insert into receipt_item (receipt_id, product_id, amount) values (4, 63, 2);
insert into receipt_item (receipt_id, product_id, amount) values (5, 39, 2);
insert into receipt_item (receipt_id, product_id, amount) values (6, 13, 2);
insert into receipt_item (receipt_id, product_id, amount) values (7, 21, 2);
insert into receipt_item (receipt_id, product_id, amount) values (8, 124, 3);
insert into receipt_item (receipt_id, product_id, amount) values (9, 138, 3);
insert into receipt_item (receipt_id, product_id, amount) values (10, 69, 1);
insert into receipt_item (receipt_id, product_id, amount) values (11, 15, 3);
insert into receipt_item (receipt_id, product_id, amount) values (12, 31, 2);
insert into receipt_item (receipt_id, product_id, amount) values (13, 113, 2);
insert into receipt_item (receipt_id, product_id, amount) values (14, 76, 1);
insert into receipt_item (receipt_id, product_id, amount) values (15, 122, 1);
insert into receipt_item (receipt_id, product_id, amount) values (16, 17, 3);
insert into receipt_item (receipt_id, product_id, amount) values (17, 126, 1);
insert into receipt_item (receipt_id, product_id, amount) values (18, 28, 3);
insert into receipt_item (receipt_id, product_id, amount) values (19, 76, 3);
insert into receipt_item (receipt_id, product_id, amount) values (20, 18, 3);
insert into receipt_item (receipt_id, product_id, amount) values (21, 7, 1);
insert into receipt_item (receipt_id, product_id, amount) values (22, 22, 2);
insert into receipt_item (receipt_id, product_id, amount) values (23, 110, 1);
insert into receipt_item (receipt_id, product_id, amount) values (24, 9, 1);
insert into receipt_item (receipt_id, product_id, amount) values (25, 111, 3);
insert into receipt_item (receipt_id, product_id, amount) values (26, 130, 3);
insert into receipt_item (receipt_id, product_id, amount) values (27, 25, 1);
insert into receipt_item (receipt_id, product_id, amount) values (28, 40, 3);
insert into receipt_item (receipt_id, product_id, amount) values (29, 64, 1);
insert into receipt_item (receipt_id, product_id, amount) values (30, 147, 2);
insert into receipt_item (receipt_id, product_id, amount) values (31, 16, 2);
insert into receipt_item (receipt_id, product_id, amount) values (32, 110, 2);
insert into receipt_item (receipt_id, product_id, amount) values (33, 42, 3);
insert into receipt_item (receipt_id, product_id, amount) values (34, 6, 3);
insert into receipt_item (receipt_id, product_id, amount) values (35, 7, 3);
insert into receipt_item (receipt_id, product_id, amount) values (36, 19, 1);
insert into receipt_item (receipt_id, product_id, amount) values (37, 74, 1);
insert into receipt_item (receipt_id, product_id, amount) values (38, 30, 3);
insert into receipt_item (receipt_id, product_id, amount) values (39, 41, 1);
insert into receipt_item (receipt_id, product_id, amount) values (40, 34, 1);
insert into receipt_item (receipt_id, product_id, amount) values (41, 22, 3);
insert into receipt_item (receipt_id, product_id, amount) values (42, 47, 2);
insert into receipt_item (receipt_id, product_id, amount) values (43, 82, 3);
insert into receipt_item (receipt_id, product_id, amount) values (44, 82, 3);
insert into receipt_item (receipt_id, product_id, amount) values (45, 49, 2);
insert into receipt_item (receipt_id, product_id, amount) values (46, 115, 3);
insert into receipt_item (receipt_id, product_id, amount) values (47, 20, 1);
insert into receipt_item (receipt_id, product_id, amount) values (48, 11, 1);
insert into receipt_item (receipt_id, product_id, amount) values (49, 89, 1);
insert into receipt_item (receipt_id, product_id, amount) values (50, 66, 2);
insert into receipt_item (receipt_id, product_id, amount) values (1, 21, 1);
insert into receipt_item (receipt_id, product_id, amount) values (2, 37, 3);
insert into receipt_item (receipt_id, product_id, amount) values (3, 56, 2);
insert into receipt_item (receipt_id, product_id, amount) values (4, 109, 1);
insert into receipt_item (receipt_id, product_id, amount) values (5, 59, 2);
insert into receipt_item (receipt_id, product_id, amount) values (6, 110, 1);
insert into receipt_item (receipt_id, product_id, amount) values (7, 61, 2);
insert into receipt_item (receipt_id, product_id, amount) values (8, 126, 2);
insert into receipt_item (receipt_id, product_id, amount) values (9, 55, 2);
insert into receipt_item (receipt_id, product_id, amount) values (10, 37, 2);
insert into receipt_item (receipt_id, product_id, amount) values (11, 99, 1);
insert into receipt_item (receipt_id, product_id, amount) values (12, 7, 2);
insert into receipt_item (receipt_id, product_id, amount) values (13, 140, 3);
insert into receipt_item (receipt_id, product_id, amount) values (14, 118, 3);
insert into receipt_item (receipt_id, product_id, amount) values (15, 142, 2);
insert into receipt_item (receipt_id, product_id, amount) values (16, 80, 3);
insert into receipt_item (receipt_id, product_id, amount) values (17, 40, 2);
insert into receipt_item (receipt_id, product_id, amount) values (18, 133, 2);
insert into receipt_item (receipt_id, product_id, amount) values (19, 19, 1);
insert into receipt_item (receipt_id, product_id, amount) values (20, 60, 3);
insert into receipt_item (receipt_id, product_id, amount) values (21, 12, 1);
insert into receipt_item (receipt_id, product_id, amount) values (22, 31, 3);
insert into receipt_item (receipt_id, product_id, amount) values (23, 113, 3);
insert into receipt_item (receipt_id, product_id, amount) values (24, 27, 3);
insert into receipt_item (receipt_id, product_id, amount) values (25, 7, 2);
insert into receipt_item (receipt_id, product_id, amount) values (26, 68, 3);
insert into receipt_item (receipt_id, product_id, amount) values (27, 62, 1);
insert into receipt_item (receipt_id, product_id, amount) values (28, 138, 1);
insert into receipt_item (receipt_id, product_id, amount) values (29, 31, 3);
insert into receipt_item (receipt_id, product_id, amount) values (30, 150, 3);
insert into receipt_item (receipt_id, product_id, amount) values (31, 12, 3);
insert into receipt_item (receipt_id, product_id, amount) values (32, 60, 1);
insert into receipt_item (receipt_id, product_id, amount) values (33, 32, 1);
insert into receipt_item (receipt_id, product_id, amount) values (34, 32, 2);
insert into receipt_item (receipt_id, product_id, amount) values (35, 4, 1);
insert into receipt_item (receipt_id, product_id, amount) values (36, 136, 2);
insert into receipt_item (receipt_id, product_id, amount) values (37, 79, 1);
insert into receipt_item (receipt_id, product_id, amount) values (38, 93, 1);
insert into receipt_item (receipt_id, product_id, amount) values (39, 37, 3);
insert into receipt_item (receipt_id, product_id, amount) values (40, 80, 1);
insert into receipt_item (receipt_id, product_id, amount) values (41, 117, 1);
insert into receipt_item (receipt_id, product_id, amount) values (42, 109, 2);
insert into receipt_item (receipt_id, product_id, amount) values (43, 28, 3);
insert into receipt_item (receipt_id, product_id, amount) values (44, 94, 1);
insert into receipt_item (receipt_id, product_id, amount) values (45, 139, 2);
insert into receipt_item (receipt_id, product_id, amount) values (46, 115, 2);
insert into receipt_item (receipt_id, product_id, amount) values (47, 138, 1);
insert into receipt_item (receipt_id, product_id, amount) values (48, 47, 2);
insert into receipt_item (receipt_id, product_id, amount) values (49, 47, 1);
insert into receipt_item (receipt_id, product_id, amount) values (50, 113, 3);
insert into receipt_item (receipt_id, product_id, amount) values (1, 121, 1);
insert into receipt_item (receipt_id, product_id, amount) values (2, 70, 1);
insert into receipt_item (receipt_id, product_id, amount) values (3, 22, 3);
insert into receipt_item (receipt_id, product_id, amount) values (4, 22, 3);
insert into receipt_item (receipt_id, product_id, amount) values (5, 127, 1);
insert into receipt_item (receipt_id, product_id, amount) values (6, 48, 1);
insert into receipt_item (receipt_id, product_id, amount) values (7, 1, 3);
insert into receipt_item (receipt_id, product_id, amount) values (8, 147, 1);
insert into receipt_item (receipt_id, product_id, amount) values (9, 79, 2);
insert into receipt_item (receipt_id, product_id, amount) values (10, 125, 3);
insert into receipt_item (receipt_id, product_id, amount) values (11, 64, 2);
insert into receipt_item (receipt_id, product_id, amount) values (12, 142, 3);
insert into receipt_item (receipt_id, product_id, amount) values (13, 31, 3);
insert into receipt_item (receipt_id, product_id, amount) values (14, 57, 3);
insert into receipt_item (receipt_id, product_id, amount) values (15, 149, 2);
insert into receipt_item (receipt_id, product_id, amount) values (16, 82, 1);
insert into receipt_item (receipt_id, product_id, amount) values (17, 51, 1);
insert into receipt_item (receipt_id, product_id, amount) values (18, 21, 3);
insert into receipt_item (receipt_id, product_id, amount) values (19, 132, 3);
insert into receipt_item (receipt_id, product_id, amount) values (20, 30, 2);
insert into receipt_item (receipt_id, product_id, amount) values (21, 53, 1);
insert into receipt_item (receipt_id, product_id, amount) values (22, 64, 2);
insert into receipt_item (receipt_id, product_id, amount) values (23, 82, 2);
insert into receipt_item (receipt_id, product_id, amount) values (24, 20, 2);
insert into receipt_item (receipt_id, product_id, amount) values (25, 70, 3);
insert into receipt_item (receipt_id, product_id, amount) values (1, 4, 2);
insert into receipt_item (receipt_id, product_id, amount) values (2, 88, 1);
insert into receipt_item (receipt_id, product_id, amount) values (3, 77, 1);
insert into receipt_item (receipt_id, product_id, amount) values (4, 68, 2);
insert into receipt_item (receipt_id, product_id, amount) values (5, 47, 3);
insert into receipt_item (receipt_id, product_id, amount) values (6, 41, 2);
insert into receipt_item (receipt_id, product_id, amount) values (7, 23, 2);
insert into receipt_item (receipt_id, product_id, amount) values (8, 101, 2);
insert into receipt_item (receipt_id, product_id, amount) values (9, 26, 3);
insert into receipt_item (receipt_id, product_id, amount) values (10, 2, 1);
insert into receipt_item (receipt_id, product_id, amount) values (11, 88, 1);
insert into receipt_item (receipt_id, product_id, amount) values (12, 85, 2);
